import { api } from './http'
import type { CreateProjectPayload, Finding, Project, ReviewTask, RiskLevel } from '../types/procurement-review'

const now = '2026-08-06T10:30:00+08:00'
const mock = import.meta.env.VITE_PROCUREMENT_REVIEW_MODE !== 'api'
const taskPath = (projectId: string, taskId = '') => `/projects/${projectId}/procurement-review-tasks${taskId ? `/${taskId}` : ''}`
const key = () => crypto.randomUUID()
let projects: Project[] = [{ id: 'prj_001', name: '2026 年办公用品采购项目', project_code: 'XMTC-CG-2026-018', handling_department: '采购业务部', project_owner: '张明', status: 'active', created_at: now, updated_at: now }]
let tasks: ReviewTask[] = [{ id: 'prt_001', project_id: 'prj_001', title: '办公用品采购文件审核', status: 'operator_review', document: { id: 'doc_001', file_name: '办公用品采购文件.docx', content_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', size: 245760, sha256: '8a7f…a31c' }, finding_summary: { total: 2, high: 1, medium: 1, low: 0, pending: 2 }, created_at: now, updated_at: now, progress: 100, parse_quality: 'passed', task_role: 'primary_supervisor', module_scope: ['procurement'] }]
let findings: Finding[] = [
  { id: 'fdg_001', task_id: 'prt_001', risk_level: 'high', category: 'compliance', title: '履约保证金与质量保证金存在重复收取风险', description: 'AI 候选问题：条款同时要求缴纳履约保证金与质量保证金，可能与适用规则冲突，须由业务人员确认。', suggestion: '建议删除重复收取的质量保证金条款，或补充适用依据。', source: { page: 18, section_path: ['第四章', '合同条款', '履约保证金'], quote: '中标人须缴纳履约保证金，并另行缴纳质量保证金。', block_id: 'blk_001' }, rule_refs: [{ id: 'R-012', title: '保证金不得重复收取' }], operator_disposition: null, primary_decision: null, collaborative_comments: [{ id: 'ccm_001', department: '财务部门', author: '周宁', comment: '建议明确保证金性质及退还条件。', updated_at: now, version: 1 }], recheck_required: true, version: 1 },
  { id: 'fdg_002', task_id: 'prt_001', risk_level: 'medium', category: 'clarity', title: '交货期表述笼统', description: 'AI 候选问题：条款仅写明“尽快交付”，缺少可执行的日历天数。', suggestion: '建议明确合同签订后完成交付的期限。', source: { page: 9, section_path: ['第三章', '商务要求', '交货期'], quote: '合同签订后尽快交付。', block_id: 'blk_002' }, rule_refs: [{ id: 'R-031', title: '交货期限应明确' }], operator_disposition: null, primary_decision: null, collaborative_comments: [], recheck_required: false, version: 1 },
]
export async function listProjects(): Promise<Project[]> { return mock ? projects : api('/projects') }
export async function createProject(payload: CreateProjectPayload): Promise<Project> { if (!mock) return api('/projects', { method: 'POST', headers: { 'Idempotency-Key': key() }, body: JSON.stringify(payload) }); const timestamp = new Date().toISOString(); const project = { id: `prj_${Date.now()}`, ...payload, status: 'active' as const, created_at: timestamp, updated_at: timestamp }; projects = [project, ...projects]; return project }
export async function getProject(id: string): Promise<Project | undefined> { return mock ? projects.find((project) => project.id === id) : api(`/projects/${id}`) }
export async function listTasks(projectId: string): Promise<ReviewTask[]> { return mock ? tasks.filter((task) => task.project_id === projectId) : api(taskPath(projectId)) }
export async function getTask(projectId: string, taskId: string): Promise<ReviewTask | undefined> { return mock ? tasks.find((task) => task.id === taskId && task.project_id === projectId) : api(taskPath(projectId, taskId)) }
export async function createTask(projectId: string, title: string, file: File): Promise<ReviewTask> { if (!mock) { const task = await api<ReviewTask>(taskPath(projectId), { method: 'POST', headers: { 'Idempotency-Key': key() }, body: JSON.stringify({ title }) }); const data = new FormData(); data.append('file', file); await api(`${taskPath(projectId, task.id)}/document`, { method: 'POST', body: data }); await api(`${taskPath(projectId, task.id)}/start`, { method: 'POST', headers: { 'Idempotency-Key': key() } }); return task } const timestamp = new Date().toISOString(); const task: ReviewTask = { id: `prt_${Date.now()}`, project_id: projectId, title, status: 'parsing', document: { id: `doc_${Date.now()}`, file_name: file.name, content_type: file.type, size: file.size, sha256: '处理中' }, finding_summary: { total: 0, high: 0, medium: 0, low: 0, pending: 0 }, created_at: timestamp, updated_at: timestamp, progress: 35, task_role: 'operator', module_scope: ['procurement'] }; tasks = [task, ...tasks]; return task }
export async function getEvents(projectId: string, taskId: string, after?: string): Promise<{ id: string }[]> { return mock ? [] : api(`${taskPath(projectId, taskId)}/events${after ? `?after=${encodeURIComponent(after)}` : ''}`) }
export async function getFindings(projectId: string, taskId: string): Promise<Finding[]> { return mock ? findings.filter((finding) => finding.task_id === taskId) : api(`${taskPath(projectId, taskId)}/findings`) }
export async function saveDisposition(projectId: string, taskId: string, findingId: string, action: 'accept' | 'partial_accept' | 'reject' | 'edit', comment: string, version: number): Promise<Finding> { if (!mock) return api(`${taskPath(projectId, taskId)}/findings/${findingId}/operator-disposition`, { method: 'PUT', body: JSON.stringify({ action, comment, version }) }); const item = findings.find((finding) => finding.id === findingId)!; item.operator_disposition = { action, comment }; item.version += 1; return item }
export async function savePrimaryDecision(projectId: string, taskId: string, findingId: string, decision: 'receive' | 'adjust' | 'reject', comment: string, risk_level: RiskLevel | undefined, version: number): Promise<Finding> { if (!mock) return api(`${taskPath(projectId, taskId)}/findings/${findingId}/primary-decision`, { method: 'PUT', body: JSON.stringify({ decision, comment, risk_level, version }) }); const item = findings.find((finding) => finding.id === findingId)!; item.primary_decision = { decision, comment, risk_level }; item.recheck_required = false; item.version += 1; return item }
export async function createCollaborativeComment(projectId: string, taskId: string, findingId: string, comment: string, version: number): Promise<Finding> { if (mock) throw new Error('协同监督意见仅在 API 联调模式可保存。'); return api(`${taskPath(projectId, taskId)}/findings/${findingId}/collaborative-comments`, { method: 'POST', body: JSON.stringify({ comment, version }) }) }
export async function updateCollaborativeComment(projectId: string, taskId: string, findingId: string, commentId: string, comment: string, version: number): Promise<Finding> { if (mock) throw new Error('协同监督意见仅在 API 联调模式可保存。'); return api(`${taskPath(projectId, taskId)}/findings/${findingId}/collaborative-comments/${commentId}`, { method: 'PUT', body: JSON.stringify({ comment, version }) }) }
export async function submitTask(projectId: string, taskId: string): Promise<void> { if (!mock) { await api(`${taskPath(projectId, taskId)}/operator-submit`, { method: 'POST', headers: { 'Idempotency-Key': key() } }); return } tasks.find((task) => task.id === taskId && task.project_id === projectId)!.status = 'primary_review' }
export async function confirmTask(projectId: string, taskId: string): Promise<void> { if (!mock) { await api(`${taskPath(projectId, taskId)}/primary-confirm`, { method: 'POST', headers: { 'Idempotency-Key': key() } }); return } tasks.find((task) => task.id === taskId && task.project_id === projectId)!.status = 'completed' }
export const usingMockProcurementService = mock
