<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import BaseModal from '../../components/base/BaseModal.vue'; import { apiErrorMessage } from '../../services/http'; import { createTask, getProject, listTasks } from '../../services/procurement-review'; import type { Project, ReviewTask } from '../../types/procurement-review'
const route = useRoute(); const router = useRouter(); const project = ref<Project>(); const tasks = ref<ReviewTask[]>([]); const loading = ref(true); const showCreate = ref(false); const title = ref(''); const file = ref<File>(); const uploadError = ref(''); const pending = ref(false); const projectId = computed(() => String(route.params.projectId)); const error = ref('')
const status: Record<string, string> = { draft: '草稿', parsing: '解析中', reviewing: 'AI 审查中', operator_review: '待经办处理', primary_review: '待主责复核', primary_recheck: '待主责再次复核', completed: '已完成', failed: '处理失败', cancelled: '已取消', queued: '排队中' }
async function load() { loading.value = true; error.value = ''; try { project.value = await getProject(projectId.value); tasks.value = await listTasks(projectId.value) } catch (reason) { error.value = apiErrorMessage(reason) } finally { loading.value = false } }
function onFile(event: Event) { const selected = (event.target as HTMLInputElement).files?.[0]; uploadError.value = ''; if (!selected) return; if (!/\.(doc|docx|pdf)$/i.test(selected.name)) { uploadError.value = '仅支持 .doc、.docx、.pdf 文件。'; return }; file.value = selected }
async function submit() { if (!file.value) { uploadError.value = '请上传一个采购文件。'; return }; pending.value = true; try { const task = await createTask(projectId.value, title.value || `${project.value?.name}采购文件审核`, file.value); router.push({ name: 'procurement-progress', params: { projectId: projectId.value, taskId: task.id } }) } catch (reason) { uploadError.value = apiErrorMessage(reason) } finally { pending.value = false } }
onMounted(load)
</script>
<template><section class="page-head"><p class="crumb"><RouterLink to="/procurement-reviews">审查任务</RouterLink> / 项目详情</p><div class="title-row"><div><h1>{{ project?.name ?? '项目不存在' }}</h1><p>{{ project?.project_code }} · {{ project?.handling_department }} · 项目负责人：{{ project?.project_owner }}</p></div><button class="button primary" :disabled="!project" @click="showCreate = true">新建采购文件审查</button></div></section><section class="page-body"><div v-if="loading" class="state-card">正在载入项目…</div><template v-else-if="project"><div class="section-title"><h2>审查子任务</h2><span>采购文件审核已开放；其他类型将在后续开放。</span></div><div v-if="tasks.length" class="task-list"><article v-for="task in tasks" :key="task.id" class="task-row"><div><span class="task-type">采购文件审查</span><h3>{{ task.title }}</h3><p>{{ task.document?.file_name ?? '尚未上传文件' }} · {{ task.created_at.slice(0,10) }}</p></div><span class="status-chip">{{ status[task.status] }}</span><button class="button" @click="router.push({ name: task.status === 'parsing' || task.status === 'reviewing' ? 'procurement-progress' : 'procurement-workbench', params: { projectId, taskId: task.id } })">查看</button></article></div><div v-else class="state-card">项目下暂无审查任务。创建项目不会上传文件，请在这里创建具体审查任务。</div><div class="future-tasks"><span>响应文件审核 · 暂未开放</span><span>合同审核 · 暂未开放</span><span>整改核销 · 暂未开放</span></div></template><div v-else class="state-card error-state">资源不存在或您无权查看。</div></section><BaseModal v-if="showCreate" title="新建采购文件审查任务" @close="showCreate=false"><form class="form-grid" @submit.prevent="submit"><label>任务名称<input v-model="title" placeholder="默认使用项目名称" /></label><label>采购文件<input type="file" accept=".doc,.docx,.pdf" required @change="onFile" /><small>仅上传一个文件，支持 DOC、DOCX、PDF。</small></label><p v-if="uploadError" class="form-error">{{ uploadError }}</p><div class="modal-actions"><button type="button" class="button" @click="showCreate=false">取消</button><button class="button primary" :disabled="pending">{{ pending ? '提交中…' : '上传并开始解析' }}</button></div></form></BaseModal></template>
