<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import AppIcon from '../../components/base/AppIcon.vue'
import FindingCard from '../../components/business/FindingCard.vue'
import { confirmTask, createCollaborativeComment, getEvents, getFindings, getTask, saveDisposition, savePrimaryDecision, submitTask, updateCollaborativeComment } from '../../services/procurement-review'
import { useAuthStore } from '../../stores/auth'
import type { Finding, ReviewTask, RiskLevel } from '../../types/procurement-review'

const route = useRoute(); const auth = useAuthStore(); const task = ref<ReviewTask>(); const findings = ref<Finding[]>([]); const filter = ref<'all' | RiskLevel>('all'); const selected = ref(''); const notice = ref(''); const busy = ref(false); const events = ref<{ id: string }[]>([])
const isReadonly = computed(() => task.value?.status === 'completed'); const mode = computed<'operator'|'primary_supervisor'|'collaborative_supervisor'|'readonly'>(() => isReadonly.value || auth.user?.roles[0]?.code === 'admin' ? 'readonly' : task.value?.task_role ?? 'readonly'); const visible = computed(() => findings.value.filter((item) => filter.value === 'all' || item.risk_level === filter.value)); const rechecks = computed(() => findings.value.filter((item) => item.recheck_required && !item.primary_decision)); const selectedFinding = computed(() => findings.value.find((item) => item.id === selected.value) ?? findings.value[0]); const cardMode = (item: Finding) => task.value?.status === 'primary_recheck' && !item.recheck_required ? 'readonly' : mode.value
async function load() { const projectId = String(route.params.projectId); const taskId = String(route.params.taskId); task.value = await getTask(projectId, taskId); if (!task.value) return; findings.value = await getFindings(projectId, taskId); events.value = await getEvents(projectId, taskId); selected.value ||= findings.value[0]?.id ?? '' }
function setFilter(value: string) { filter.value = value as 'all' | RiskLevel }
function message(error: unknown) { const status = (error as { status?: number }).status; return status === 409 ? '数据已被他人修改，请刷新后重新确认。' : status === 403 ? '无权执行该操作。' : status === 422 ? '填写内容不符合要求。' : '操作失败，请稍后重试。' }
async function disposition(item: Finding, action: 'accept'|'partial_accept'|'reject'|'edit', comment: string) { if (!task.value) return; busy.value = true; try { await saveDisposition(task.value.project_id, task.value.id, item.id, action, comment, item.version); notice.value = '经办处置已保存。'; await load() } catch (error) { notice.value = message(error) } finally { busy.value = false } }
async function primary(item: Finding, decision: 'receive'|'adjust'|'reject', comment: string, risk: RiskLevel | undefined) { if (!task.value) return; busy.value = true; try { await savePrimaryDecision(task.value.project_id, task.value.id, item.id, decision, comment, risk, item.version); notice.value = '主责复核意见已保存。'; await load() } catch (error) { notice.value = message(error) } finally { busy.value = false } }
async function collaborative(item: Finding, comment: string) { if (!task.value) return; const own = item.collaborative_comments.find((entry) => entry.author === auth.user?.display_name); try { if (own) await updateCollaborativeComment(task.value.project_id, task.value.id, item.id, own.id, comment, own.version); else await createCollaborativeComment(task.value.project_id, task.value.id, item.id, comment, item.version); notice.value = '协同监督意见已保存。'; await load() } catch (error) { notice.value = message(error) } }
async function submit() { if (!task.value) return; busy.value = true; try { await submitTask(task.value.project_id, task.value.id); notice.value = '已提交采购部门主责监督复核。'; await load() } catch (error) { notice.value = message(error) } finally { busy.value = false } }
async function confirm() { if (!task.value) return; busy.value = true; try { await confirmTask(task.value.project_id, task.value.id); notice.value = '正式复核结果已确认，任务已锁定为只读。'; await load() } catch (error) { notice.value = message(error) } finally { busy.value = false } }
onMounted(load)
</script>

<template>
  <section class="page-head workbench-head">
    <p class="crumb">审查任务 / {{ task?.project_id }} / 采购文件审核</p>
    <div class="title-row"><div><h1>{{ task?.title ?? '审查工作台' }}</h1><p>AI 输出仅为候选问题，原文、规则依据与人工处置在同一审查记录中留痕。</p></div><span class="title-status">{{ isReadonly ? '已完成 · 只读' : task?.status === 'primary_recheck' ? '待采购监督再次复核' : '审查进行中' }}</span></div>
  </section>
  <section class="page-body workbench-page">
    <div v-if="notice" class="notice" role="status">{{ notice }}</div><div v-if="!task" class="state-card error-state">资源不存在或无权查看。</div>
    <template v-else>
      <div class="review-actions"><div><b>当前阶段：</b>{{ isReadonly ? '正式复核已确认' : task.status === 'operator_review' ? '业务经办处置 AI 候选问题' : task.status === 'primary_recheck' ? '主责监督再次复核受影响条目' : '采购部门主责监督复核' }}</div><span class="spacer" /><button v-if="mode === 'operator'" class="button primary" :disabled="busy || findings.some((item) => !item.operator_disposition)" @click="submit">确认审查结果</button><button v-if="mode === 'primary_supervisor'" class="button primary" :disabled="busy || (task.status === 'primary_recheck' ? rechecks.length > 0 : findings.some((item) => !item.primary_decision))" @click="confirm">确认复核结果</button></div>
      <div v-if="isReadonly" class="readonly-banner">此任务已完成，所有写入动作均已禁用；可继续查看完整证据链和审计记录。</div>
      <div class="workbench-grid">
        <aside class="work-column doc-column"><header class="work-column-head"><span>采购文档</span><small>{{ task.document?.file_name }}</small></header><div class="work-column-body"><div class="doc-item sel"><div><AppIcon name="file" :size="15" />采购文件</div><small>{{ task.document?.file_name }} · 当前版本</small></div><div v-for="entry in [['第四章','合同条款'],['§5.3','履约保证金'],['§4.2','交货要求'],['§8.1','付款期限'],['附件第 18 页','授权与技术资料']]" :key="entry[0]" class="clause" :class="{ hot: entry[0] === '§5.3' }"><small>{{ entry[0] }}</small><p>{{ entry[1] }}</p><span v-if="entry[0] === '§5.3'">履约保证金与质量保证金条款</span></div></div></aside>
        <main class="work-column evidence-column"><header class="work-column-head"><span>原文与证据定位</span><div class="head-actions"><AppIcon name="search" :size="15" /><button class="text-button">定位第 {{ selectedFinding?.source.page ?? '—' }} 页</button></div></header><div class="work-column-body evidence-paper"><article class="paper-sheet"><p class="paper-kicker">{{ task.document?.file_name }}</p><h2>采购文件 · 原文证据</h2><p>第四章　合同条款</p><p :class="{ 'evidence-hot': selectedFinding?.id === 'fdg_001' }">5.3 中标人须按合同金额 5% 缴纳履约保证金，并另行缴纳质量保证金。</p><p :class="{ 'evidence-hot': selectedFinding?.id === 'fdg_002' }">4.2 交货期：合同签订后尽快交付。</p><p>8.1 验收合格并收到发票后 90 日内完成付款。</p><div class="paper-locator"><AppIcon name="ruler" :size="15" />{{ selectedFinding?.source.section_path.join(' / ') }} · 第 {{ selectedFinding?.source.page }} 页</div></article><section class="evidence-meta"><h3>审查依据</h3><div v-for="rule in selectedFinding?.rule_refs" :key="rule.id" class="rule-ref"><AppIcon name="scale" :size="15" /><b>{{ rule.id }}</b><span>{{ rule.title }}</span></div><div class="evidence-note"><AppIcon name="shield" :size="15" />原文证据与规则依据均需人工确认，不构成自动审批结论。</div></section></div></main>
        <aside class="work-column finding-column"><header class="work-column-head"><span>审查结论</span><small>{{ findings.length }} 项 AI 候选</small></header><div class="finding-toolbar"><span>风险筛选</span><button v-for="item in [['all','全部'],['high','高风险'],['medium','中风险'],['low','低风险'],['unknown','证据不足']]" :key="item[0]" class="filter-btn" :class="{ on: filter === item[0] }" @click="setFilter(item[0])">{{ item[1] }}</button></div><div class="work-column-body finding-list"><button v-for="item in visible" :key="item.id" class="finding-nav" :class="{ active: selected === item.id, recheck: item.recheck_required }" @click="selected = item.id"><span :class="`risk-dot ${item.risk_level}`" /><span>{{ item.title }}</span><small>{{ item.risk_level === 'high' ? '高风险' : item.risk_level === 'medium' ? '中风险' : item.risk_level === 'unknown' ? '证据不足' : '低风险' }}</small></button><FindingCard v-if="selectedFinding" :finding="selectedFinding" :mode="cardMode(selectedFinding)" @disposition="(action, comment) => disposition(selectedFinding!, action, comment)" @decision="(action, comment, risk) => primary(selectedFinding!, action, comment, risk)" @opinion="(comment) => collaborative(selectedFinding!, comment)" /><section class="audit-trail"><h3>审计时间线</h3><p><i />AI 审查生成候选问题与证据</p><p v-for="event in events.slice(0, 4)" :key="event.id"><i />任务事件 {{ event.id }}</p><p><i />当前状态：{{ task.status }}</p></section></div></aside>
      </div>
    </template>
  </section>
</template>
