<script setup lang="ts">
import { computed, ref } from 'vue'
import type { Finding, RiskLevel } from '../../types/procurement-review'
const props = defineProps<{ finding: Finding; mode: 'operator' | 'primary_supervisor' | 'collaborative_supervisor' | 'readonly' }>()
const emit = defineEmits<{ disposition: [action: 'accept' | 'partial_accept' | 'reject' | 'edit', comment: string]; decision: [decision: 'receive' | 'adjust' | 'reject', comment: string, risk: RiskLevel | undefined]; opinion: [comment: string] }>()
const comment = ref(''); const opinion = ref(''); const decisionRisk = ref<RiskLevel>(props.finding.risk_level)
const labels: Record<RiskLevel, string> = { high: '高风险', medium: '中风险', low: '低风险', unknown: '证据不足' }
const actionName = computed(() => props.finding.operator_disposition ? '已保存经办意见' : '等待经办处置')
function disposition(action: 'accept' | 'partial_accept' | 'reject' | 'edit') { if ((action === 'partial_accept' || action === 'reject' || action === 'edit') && !comment.value.trim()) return; emit('disposition', action, comment.value) }
</script>
<template><article class="finding-card" :class="`risk-${finding.risk_level}`"><div class="finding-heading"><span class="risk-tag" :class="`risk-${finding.risk_level}`">{{ labels[finding.risk_level] }}</span><span class="ai-tag">AI 候选问题</span><span v-if="finding.recheck_required" class="recheck-tag">待采购监督再次复核</span></div><h3>{{ finding.title }}</h3><p>{{ finding.description }}</p><dl class="evidence-grid"><div><dt>修改建议</dt><dd>{{ finding.suggestion }}</dd></div><div><dt>原文证据 · 第 {{ finding.source.page }} 页</dt><dd><button type="button" class="text-button">{{ finding.source.quote }}</button></dd></div><div><dt>章节路径</dt><dd>{{ finding.source.section_path.join(' / ') }}</dd></div><div><dt>规则依据</dt><dd>{{ finding.rule_refs.map((rule) => `${rule.id} ${rule.title}`).join('；') }}</dd></div></dl><div class="opinion-block"><b>经办意见</b><span>{{ finding.operator_disposition ? `${finding.operator_disposition.action}：${finding.operator_disposition.comment || '已确认'}` : '尚未处置' }}</span></div><div class="opinion-block"><b>主责监督意见</b><span>{{ finding.primary_decision ? `${finding.primary_decision.decision}：${finding.primary_decision.comment || '已确认'}` : '尚未复核' }}</span></div><div v-if="finding.collaborative_comments.length" class="opinions"><b>协同监督意见</b><p v-for="item in finding.collaborative_comments" :key="item.id"><strong>{{ item.department }}</strong>：{{ item.comment }}</p></div><p class="finding-state">当前状态：{{ actionName }}</p><template v-if="mode === 'operator'"><textarea v-model="comment" aria-label="经办意见" placeholder="部分采纳、不采纳或修改意见时必须填写理由" /><div class="action-row"><button class="button" @click="disposition('accept')">采纳</button><button class="button" @click="disposition('partial_accept')">部分采纳</button><button class="button" @click="disposition('reject')">不采纳</button><button class="button" @click="disposition('edit')">修改意见</button></div></template><template v-else-if="mode === 'primary_supervisor'"><textarea v-model="comment" aria-label="主责监督意见" placeholder="填写复核意见" /><select v-model="decisionRisk" aria-label="调整风险等级"><option value="high">高风险</option><option value="medium">中风险</option><option value="low">低风险</option><option value="unknown">证据不足</option></select><div class="action-row"><button class="button" @click="$emit('decision','receive',comment, undefined)">接收</button><button class="button" @click="$emit('decision','adjust',comment, decisionRisk)">调整</button><button class="button" @click="$emit('decision','reject',comment, undefined)">拒绝</button></div></template><template v-else-if="mode === 'collaborative_supervisor'"><textarea v-model="opinion" aria-label="协同监督意见" placeholder="填写或修改本部门专业意见" /><button class="button" :disabled="!opinion.trim()" @click="$emit('opinion', opinion)">保存本部门意见</button></template></article></template>
